### ISSUE TITLE
UIをカッコよくする

### ISSUE THREAD

**Issue by Alicelavander** [Alicelavander/To-Do-List#1]
UIをカッコよくするやり方がわからない-調べてないからです！

**Comment by yokmama** [comment]
やり方がわからないの理由に
　Dartのコーディングがわからない
　Flutterのレイアウトがわからない
　なにができるかわからない

というレベルがあるのだけど、どこだとおもいますか？

**Comment by Alicelavander** [comment]
なにができるかわからない
